site_name: "FunFact: Tensor Algebra and Deep Learning via Einstein Notations"
theme:
  name: material
  logo: assets/funfact.svg
  palette:
    scheme: default
    primary: amber
  features:
    content.code.annotate
plugins:
  - search
  - mkdocstrings
nav:
    - Home: index.md
    - Installation: installation.md
    - Examples:
      - Nonlinear matrix approximation: "examples/nma.md"
    - User Guide: ug.md
    - API Reference: api.md
    - How to contribute: contribute.md
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js