site_name: "FunFact: Tensor Algebra and Deep Learning via Einstein Notations"
theme:
  name: material
  logo: assets/funfact.svg
  favicon: assets/favicon.png
  palette:
    scheme: default
    primary: amber
  features:
    content.code.annotate
plugins:
  - search
  - autorefs
  - mkdocstrings:
      watch:
        - funfact
  # - gen-files:
  #     scripts:
  #     - docs/gen_ref_nav.py
      # - docs/gen_credits.py
nav:
    - Home: index.md
    - Installation: pages/installation.md
    - Examples:
      - Nonlinear matrix approximation: pages/examples/nma.md
    - User Guide:
        Overview: pages/user_guide.md
        Grammar reference: pages/tsrex.md
    - API Reference:
        "funfact.active_backend": api/active_backend.md
        "funfact.available_backends": api/available_backends.md
        "funfact.use": api/use.md
        "funfact.factorize": api/factorize.md
        "funfact.Factorization": api/factorization.md
        "funfact.tensor": api/tensor.md
        "funfact.index": api/index.md
        "funfact.indices": api/indices.md
    # - API Reference: reference/
    - How to contribute: pages/contribute.md
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - pymdownx.details
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js