# Badge generation workflow
name: Badge
on:
  push:
    # branches:
    #   - master
    #   - develop
  workflow_dispatch:
jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Coverage Test
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - id: tox
        name: Launch Tox environment
        uses: yhtang/tox-github-action@master
        with:
          tox_env: coverage
      - id: test
        name: test command
        run: |
          echo "::set-output name=test::ABC"
      - name: Get coverage number
        # run: >
        #   echo "${{ steps.tox.outputs }}"
        #   | awk '/^TOTAL\s+[0-9]+\s+[0-9]+\s+([0-9]+%)/ { print "::set-env name=COVERAGE::"$4 }'
        run: |
          echo "TEST1______________________________"
          echo "${{ steps.tox.outputs }}"
          echo "TEST2______________________________"
          echo ${{ steps.tox.outputs }}
          echo "TEST3______________________________"
          echo ${{ join(steps.tox.outputs.*, '\n') }}
          echo "TEST4______________________________"
          echo ${{ join(steps.test.outputs.*, '\n') }}
          echo "TEST*______________________________"
          echo | awk '{ print "A="3 }' >> $GITHUB_ENV
      - name: Create badge endpoint
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.CI_COVERAGE_BADGE_GIST }}
          gistID: 839011f3f7a6bab680b18cbd9a45d2d3
          # filename: coverage-${{ github.ref }}.json
          filename: badge.json
          label: code coverage
          # message: $COVERAGE
          message: ${{ env.A }}
          color: blue
