# Use tests defined in tox.ini

name: Tox

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tox:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: fedora-python/tox-github-action@v0.4
        with:
          tox_env: ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env: [py37, py38, py39, coverage]
